# Generated by Django 5.1.2 on 2024-10-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedidos', models.DateField(auto_now_add=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('productos', models.ManyToManyField(to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedidos')),
            ],
        ),
    ]
